 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     docker:
       - image: microsoft/dotnet:sdk
     environment:
       DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
       DOTNET_CLI_TELEMETRY_OPTOUT: 1
     
     steps:
       - checkout
       - run: dotnet restore
       - run: dotnet build
       - run: dotnet run --project ./AzureBlobPhotos/AzureBlobPhotos.csproj
      
 workflows:
  version: 2
  workflow:
    jobs:
    - build

# version: 2.1

#orbs:
#  win: circleci/windows@1.0.0

#jobs:
#  build:
#    executor:
#      name: win/vs2019
#      shell: powershell.exe
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
#      - run:
#          name: "Install project dependencies"
#          command: dotnet.exe restore
#      - save_cache:
#          paths:
#            - C:\Users\circleci\.nuget\packages
#          key: dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
#      - run:
#          name: "Run Build step"
#          command: dotnet.exe publish -c Release -r win10-x64
#      - run:
#          name: "Test the executable"
#          command: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe
#      - store_artifacts:
#          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe
